# -*- coding: utf-8 -*-
"""diabetes_cleaned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11W_0vKRuN29V22fVYEnZbMgIYFlUAhLX
"""

import pandas as pd
import numpy as np
import streamlit as st

"""###Importing the dataset

"""

df=pd.read_csv('diabetes.csv')
df.head()

df.shape

df.columns

df.rename(columns={'No_Pation':'Patients'},inplace=True)

df.columns

df.info()

df['CLASS'].value_counts()

df['CLASS'].unique()

df['CLASS']=df['CLASS'].replace(['Y ','N '],['Y','N'] )

df.CLASS.unique()

df.isnull().sum()

df.boxplot('Cr',vert=False,grid=False)

"""###removing outliers using z-score"""

from scipy import stats
df.dropna(subset='Cr',inplace=True)
z_score=stats.zscore(df['Cr'])
pd.DataFrame({'CR':df['Cr'],'Z_score':z_score}).head()

df = df[abs(z_score)<=2]

df.shape

df.boxplot('Cr',vert=False,grid=False)

df.boxplot('HbA1c' ,vert=False,grid=False)

mean_hb=df['HbA1c'].mean()
df['HbA1c']=df['HbA1c'].fillna(mean_hb)

df.boxplot('Chol' ,vert=False,grid=False)

median_ch=df['Chol'].median()
df['Chol']=df['Chol'].fillna(median_ch)

df.dropna(inplace=True)

df.isna().sum()

st.dataframe(df)
df.to_csv('diabetes_cleaned.csv')

